services:
  unbound:
    image: mvance/unbound-rpi:latest # ARM-compatible build
    container_name: unbound
    restart: unless-stopped
    volumes:
      - ./unbound-conf/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    networks:
      adguard-net:
        ipv4_address: 172.20.0.2
    cap_add:
      - NET_ADMIN
